name: Update README

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Runs on commits to the main branch

jobs:
  update-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build and Execute Rust Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd github-readme-generator
          cargo build --release
          ./target/release/github-readme-generator

      - name: Commit and Push Changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git stash --include-untracked # Stash all changes
          git pull --rebase # Pull the latest changes
          git stash pop # Reapply stashed changes
          git add README.md
          git commit -m "🔄 Update README" || echo "No changes to commit"
          git push || echo "No changes to push"
